baseURL = "https://example.com/"
languageCode = "en-us"
title = "DotFrames"
paginate = 15
enableRobotsTXT = true
[params]
  description = "Frame by frame anime reviews"
  author = "DotFrames Team"
[outputs]
  home = ["HTML", "RSS"]
[sitemap]
  changefreq = "daily"
  priority = 0.8
[markup.goldmark.renderer]
  unsafe = true
